### ISSUE TITLE
About speech positional embedding

### ISSUE THREAD

**Issue by world1tree** [ictnlp/CRESS#6]
https://github.com/ictnlp/CRESS/blob/a701837c6d2b6cf8f4e833c03716f97cd1560688/cress/models/hubert_transformer.py#L382C39-L382C39

Hello. The positional information is not added after `_get_hubert_features and subsampler`. Does it have any impact on the final result?

**Comment by Poeroz** [comment]
Hello. Thanks for your question. Since HuBERT already adds positional embeddings to the input audio signal, we didn't add positional information to the HuBERT output features. We are not sure what if add it again.
